<?php
$data = $this->view_data ?: array();
$avatar_url = null;
if (!empty($data['pict'])) {
  $clean_path = ltrim(str_replace(array('../', '..\\'), '', $data['pict']), '/');
  $real_file = realpath(ROOT . $clean_path); $uploads_root = realpath(ROOT . 'uploads');
  if ($real_file && $uploads_root && strpos($real_file, $uploads_root . DIRECTORY_SEPARATOR) === 0 && is_file($real_file)) { $avatar_url = get_link($clean_path); }
}
$model = new SharedController; $role_label = $data['user_role_id'] ?? '-';
foreach ($model->users_user_role_id_option_list() as $option) { if (($option['value'] ?? null) == ($data['user_role_id'] ?? null)) { $role_label = $option['label']; break; } }
$status = $data['account_status'] ?? '-'; $status_class = strtolower($status) === 'active' ? 'success' : (in_array(strtolower($status), array('pending','pending_activation')) ? 'warning' : 'secondary');
?>
<section class="page"><div class="bg-light p-3 mb-3"><div class="container"><h4 class="record-title">My Account</h4></div></div>
<div class="container"><?php $this::display_page_errors(); ?><div class="card shadow-sm"><div class="card-body">
<div class="bg-primary rounded text-center text-white p-4 mb-4"><div class="mb-2"><?php if ($avatar_url) { ?><img src="<?php echo htmlspecialchars($avatar_url, ENT_QUOTES, 'UTF-8'); ?>" class="rounded-circle" style="width:90px;height:90px;object-fit:cover" alt="Foto profil"><?php } else { ?><i class="fa fa-user-circle" style="font-size:90px"></i><?php } ?></div><h4 class="mb-0"><?php echo htmlspecialchars($data['username'] ?? '-'); ?></h4></div>
<div class="row"><div class="col-md-3"><div class="nav nav-pills flex-column"><a class="nav-link active" data-toggle="tab" href="#account-detail">Account Detail</a><a class="nav-link" data-toggle="tab" href="#account-paraf"><i class="fa fa-pencil-square-o mr-1"></i> Paraf Digital</a><a class="nav-link" data-toggle="tab" href="#account-edit">Edit Account</a><a class="nav-link" data-toggle="tab" href="#account-email">Change Email</a><a class="nav-link" data-toggle="tab" href="#account-password">Ganti Password</a></div></div>
<div class="col-md-9"><div class="tab-content"><div class="tab-pane fade show active" id="account-detail"><table class="table table-striped"><tr><th>Nama</th><td><?php echo htmlspecialchars($data['nama'] ?? '-'); ?></td></tr><tr><th>Email</th><td><?php echo htmlspecialchars($data['email'] ?? '-'); ?></td></tr><tr><th>NIK</th><td><?php echo htmlspecialchars($data['username'] ?? '-'); ?></td></tr><tr><th>Area</th><td><?php echo htmlspecialchars($data['area'] ?? '-'); ?></td></tr><tr><th>Mesin</th><td><?php echo htmlspecialchars($data['mesin'] ?? '-'); ?></td></tr><tr><th>Status</th><td><span class="badge badge-<?php echo $status_class; ?>"><?php echo htmlspecialchars($status); ?></span></td></tr><tr><th>Role</th><td><?php echo htmlspecialchars($role_label); ?></td></tr><tr><th>Foto</th><td><?php if ($avatar_url) { ?><img src="<?php echo htmlspecialchars($avatar_url, ENT_QUOTES, 'UTF-8'); ?>" class="rounded" style="width:48px;height:48px;object-fit:cover" alt="Foto profil"><?php } else { ?>Belum ada foto<?php } ?></td></tr><tr><th>Paraf Digital</th><td><?php if (!empty($data['paraf_image'])) { ?><img src="<?php echo htmlspecialchars($data['paraf_image'], ENT_QUOTES, 'UTF-8'); ?>" class="rounded bg-white border p-1" style="height:36px;object-fit:contain" alt="Paraf Digital"><?php } else { ?><span class="badge badge-light border px-2 py-1"><?php echo htmlspecialchars($data['user_initials'] ?: 'Belum diatur'); ?></span><?php } ?></td></tr></table></div>
<div class="tab-pane fade" id="account-paraf"><?php $this->render_page('account/paraf'); ?></div><div class="tab-pane fade" id="account-edit"><?php $this->render_page('account/edit'); ?></div><div class="tab-pane fade" id="account-email"><?php $this->render_page('account/change_email'); ?></div><div class="tab-pane fade" id="account-password"><?php $this->render_page('account/change_password'); ?></div></div></div></div>
</div></div></div></section>
