-- Skema PostgreSQL Form AM
-- Digenerate dari ddl_dml.sql + database/migrations/*.sql
-- Tabel pabrik sebelah (33) dan illapak_1..12 legacy TIDAK disertakan.

CREATE TABLE IF NOT EXISTS "approval" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY,
  "Timestamp" varchar(255) DEFAULT NULL,
  "id_log" varchar(255) DEFAULT NULL,
  "Action" varchar(255) DEFAULT NULL,
  "TableName" varchar(255) DEFAULT NULL,
  "UserID" varchar(255) DEFAULT NULL,
  "SQLQuery" text DEFAULT NULL,
  "ServerIP" varchar(255) DEFAULT NULL,
  "RequestURL" varchar(255) DEFAULT NULL,
  "RequestData" text DEFAULT NULL,
  "RequestCompleted" varchar(255) DEFAULT NULL,
  "RequestMsg" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("log_id")
);

CREATE TABLE IF NOT EXISTS "kategori" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "korelasi_id" integer NOT NULL,
  "kategori" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "klasifikasi" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "korelasi" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mesin" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama_mesin" varchar(255) DEFAULT NULL,
  "nomor_seri" varchar(50) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "roles" (
  "role_id" integer GENERATED BY DEFAULT AS IDENTITY,
  "role_name" varchar(255) NOT NULL,
  PRIMARY KEY ("role_id")
);

CREATE TABLE IF NOT EXISTS "tb_mesin_sig" (
  "id_sig" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_cross_dan_vertikal" varchar(255) DEFAULT NULL,
  "guarding_akrilik" varchar(255) DEFAULT NULL,
  "jalur_conveyor" varchar(255) DEFAULT NULL,
  "antistatic" varchar(255) DEFAULT NULL,
  "vacuum_hood" varchar(255) DEFAULT NULL,
  "tekanan_angin_suplai" varchar(255) DEFAULT NULL,
  "value_tekanan_angin" numeric(4,2) DEFAULT NULL,
  "jarak_slider_dengan_nozzle" varchar(255) DEFAULT NULL,
  "rol_penarik_sachet_dan_foil_slitting_shim" varchar(255) DEFAULT NULL,
  "pisau_belah" varchar(255) DEFAULT NULL,
  "modul_pisau" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_sig")
);

CREATE TABLE IF NOT EXISTS "kendala_sig" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

CREATE TABLE IF NOT EXISTS "tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "kategori_tag" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "users" (
  "id_user" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "username" varchar(255) NOT NULL,
  "area" varchar(255) DEFAULT NULL,
  "mesin" varchar(255) DEFAULT NULL,
  "password" varchar(255) DEFAULT NULL,
  "login_session_key" varchar(255) DEFAULT NULL,
  "email_status" varchar(255) DEFAULT NULL,
  "password_expire_date" date DEFAULT NULL,
  "password_reset_key" varchar(255) DEFAULT NULL,
  "account_status" varchar(255) DEFAULT 'Pending',
  "user_role_id" integer DEFAULT NULL,
  "pict" varchar(255) DEFAULT NULL,
  "failed_login_attempts" integer DEFAULT 0,
  "is_super_admin" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id_user")
);
-- Cuma boleh ada 1 baris is_super_admin=true di seluruh tabel -- dijaga di
-- level DB, bukan cuma diasumsikan lewat kode. Lihat
-- database/migrations/2026-08-20_add_super_admin_protection.sql.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_single_super_admin"
  ON "users" ((is_super_admin))
  WHERE is_super_admin = true;

-- dari 2026-08-07_create_joeya.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_joeya" (
  "id_joeya" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "jalur_konveyor_sachet" varchar(255) DEFAULT NULL,
  "collecting_plate_seluncuran_sachet" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_joeya")
);

-- dari 2026-08-07_create_joeya.sql
CREATE TABLE IF NOT EXISTS "kendala_joeya" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-07_create_illapak_1_2.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_illapak_1_2" (
  "id_illapak_1_2" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "position_indicator_sealing_vertical" varchar(255) DEFAULT NULL,
  "vacum_sliter" varchar(255) DEFAULT NULL,
  "piston_pengisian" varchar(255) DEFAULT NULL,
  "pneumatic_valves_pengisian" varchar(255) DEFAULT NULL,
  "baut_sealing_vertikal" varchar(255) DEFAULT NULL,
  "rubber_penarik_foil" varchar(255) DEFAULT NULL,
  "sensor_eyemark_dan_sambungan_foil" varchar(255) DEFAULT NULL,
  "guarding_mesin" varchar(255) DEFAULT NULL,
  "pressure_blow_sealing_vertical" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "pengunci_nozzle_pengisian" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_illapak_1_2")
);

-- dari 2026-08-07_create_illapak_1_2.sql
CREATE TABLE IF NOT EXISTS "kendala_illapak_1_2" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer NOT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) NOT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- dari 2026-08-07_create_illapak_3_12.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_illapak_3_12" (
  "id_illapak_3_12" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "position_indicator_sealing_vertical" varchar(255) DEFAULT NULL,
  "vacum_sliter" varchar(255) DEFAULT NULL,
  "alarm_temperature" varchar(255) DEFAULT NULL,
  "piston_pengisian" varchar(255) DEFAULT NULL,
  "pneumatic_valves_pengisian" varchar(255) DEFAULT NULL,
  "baut_sealing_vertikal" varchar(255) DEFAULT NULL,
  "rubber_penarik_foil" varchar(255) DEFAULT NULL,
  "sensor_eyemark_dan_sambungan_foil" varchar(255) DEFAULT NULL,
  "guarding_mesin" varchar(255) DEFAULT NULL,
  "pressure_blow_sealing_vertical" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "pengunci_nozzle_pengisian" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_illapak_3_12")
);

-- dari 2026-08-07_create_illapak_3_12.sql
CREATE TABLE IF NOT EXISTS "kendala_illapak_3_12" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer NOT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) NOT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- dari 2026-08-07_create_unifill_b.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_unifill_b" (
  "id_unifill_b" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor" varchar(255) DEFAULT NULL,
  "cutting_unit" varchar(255) DEFAULT NULL,
  "neck_sealing_unit" varchar(255) DEFAULT NULL,
  "nozzle" varchar(255) DEFAULT NULL,
  "tekanan_angin" varchar(255) DEFAULT NULL,
  "temperature_air_pendingin" varchar(255) DEFAULT NULL,
  "piston_valves_dan_selang_pengisian" varchar(255) DEFAULT NULL,
  "buffer_roller_dispenser" varchar(255) DEFAULT NULL,
  "sensory_eyemark_sensor_redaksi" varchar(255) DEFAULT NULL,
  "cylinder_grip" varchar(255) DEFAULT NULL,
  "timing_belt_pengisian" varchar(255) DEFAULT NULL,
  "filter_airfan" varchar(255) DEFAULT NULL,
  "guide_nozzle" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_unifill_b")
);

-- dari 2026-08-07_create_unifill_b.sql
CREATE TABLE IF NOT EXISTS "kendala_unifill_b" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_chimei.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_chimei" (
  "id_chimei" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor_produk" varchar(255) DEFAULT NULL,
  "roller_opp" varchar(255) DEFAULT NULL,
  "rantai_opp" varchar(255) DEFAULT NULL,
  "bearing_break_opp" varchar(255) DEFAULT NULL,
  "rantai_motor_utama_cam" varchar(255) DEFAULT NULL,
  "as_pendorong_pack" varchar(255) DEFAULT NULL,
  "jalur_compressed_air" varchar(255) DEFAULT NULL,
  "air_regulator" varchar(255) DEFAULT NULL,
  "sensor_produk_opp_pack" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_chimei")
);

-- dari 2026-08-11_create_chimei.sql
CREATE TABLE IF NOT EXISTS "kendala_chimei" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_temach.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_temach" (
  "id_temach" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor_produk" varchar(255) DEFAULT NULL,
  "pusher_pendorong_pack" varchar(255) DEFAULT NULL,
  "turet" varchar(255) DEFAULT NULL,
  "cam" varchar(255) DEFAULT NULL,
  "lubrikasi_bearing_konveyor" varchar(255) DEFAULT NULL,
  "jalur_compressed_air" varchar(255) DEFAULT NULL,
  "air_regulator" varchar(255) DEFAULT NULL,
  "heater_a_f" varchar(255) DEFAULT NULL,
  "baut_turet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_temach")
);

-- dari 2026-08-11_create_temach.sql
CREATE TABLE IF NOT EXISTS "kendala_temach" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jihcheng.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_jihcheng" (
  "id_jihcheng" integer GENERATED BY DEFAULT AS IDENTITY,
  "konveyor_belt" varchar(255) DEFAULT NULL,
  "flexible_konveyor_u" varchar(255) DEFAULT NULL,
  "suction_cup" varchar(255) DEFAULT NULL,
  "pocket_pembawa_tube_dan_pack" varchar(255) DEFAULT NULL,
  "shaft_dan_bushing_pusher" varchar(255) DEFAULT NULL,
  "bearing_rantai_tube_cam_pusher" varchar(255) DEFAULT NULL,
  "rantai_penggerak_utama_pocket_tube_pack" varchar(255) DEFAULT NULL,
  "regulator_angin_utama" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_tube_pack_nozzle_lem" varchar(255) DEFAULT NULL,
  "pengecekan_tombol_emergency" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jihcheng")
);

-- dari 2026-08-11_create_jihcheng.sql
CREATE TABLE IF NOT EXISTS "kendala_jihcheng" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_jinsung_1_4" (
  "id_jinsung_1_4" integer GENERATED BY DEFAULT AS IDENTITY,
  "flexible_conveyor_infeed_belt_conveyor" varchar(255) DEFAULT NULL,
  "pocket_pembawa_sachet" varchar(255) DEFAULT NULL,
  "shaft_bushing_pusher_stacking" varchar(255) DEFAULT NULL,
  "rantai_penggerak" varchar(255) DEFAULT NULL,
  "regulator_angin_stacking_cartoning_check_weigher" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_sachet_pack_nozzle" varchar(255) DEFAULT NULL,
  "penekan_sachet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jinsung_1_4")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "kendala_jinsung_1_4" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_jinsung_5" (
  "id_jinsung_5" integer GENERATED BY DEFAULT AS IDENTITY,
  "belt_conveyor_dan_pusher_pack" varchar(255) DEFAULT NULL,
  "pocket_pembawa_sachet" varchar(255) DEFAULT NULL,
  "shaft_bushing_pusher_piston" varchar(255) DEFAULT NULL,
  "rantai_penggerak_utama_cartoning" varchar(255) DEFAULT NULL,
  "regulator_angin_conveyor_cartoning_check_weigher" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_sachet_pack_nozzle" varchar(255) DEFAULT NULL,
  "timing_belt_conveyor" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jinsung_5")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "kendala_jinsung_5" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_best_pack.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_best_pack" (
  "id_best_pack" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_best_pack" varchar(255) DEFAULT NULL,
  "konveyor_best_pack" varchar(255) DEFAULT NULL,
  "print_head_inkjet" varchar(255) DEFAULT NULL,
  "belt_conveyor_best_pack" varchar(255) DEFAULT NULL,
  "pisau_best_pack" varchar(255) DEFAULT NULL,
  "selang_angin_best_pack" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_best_pack")
);

-- dari 2026-08-11_create_best_pack.sql
CREATE TABLE IF NOT EXISTS "kendala_best_pack" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_cosmec.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_cosmec" (
  "id_cosmec" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_panel_hmi" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "pengunci_bin" varchar(255) DEFAULT NULL,
  "switch_rantai" varchar(255) DEFAULT NULL,
  "as_dan_flange_tumbler" varchar(255) DEFAULT NULL,
  "baut_dan_mur_pada_flange_shaft" varchar(255) DEFAULT NULL,
  "panel_pompa_hidrolik_mesin" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_cosmec")
);

-- dari 2026-08-11_create_cosmec.sql
CREATE TABLE IF NOT EXISTS "kendala_cosmec" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_fbd_jaw_chuan.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_fbd_jaw_chuan" (
  "id_fbd_jaw_chuan" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "panel_fbd" varchar(255) DEFAULT 'OK',
  "tombol_tombol_pada_panel_fbd" varchar(255) DEFAULT 'OK',
  "seal_bagtight" varchar(255) DEFAULT 'OK',
  "container_up_down" varchar(255) DEFAULT 'OK',
  "shaking" varchar(255) DEFAULT 'OK',
  "pressure_gauge_damper" varchar(255) DEFAULT 'OK',
  "seal_container" varchar(255) DEFAULT 'OK',
  "guarding_pengunci_kontainer" varchar(255) DEFAULT 'OK',
  "container_mesh_dan_roda" varchar(255) DEFAULT 'OK',
  "filter_dan_bag_tight" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_fbd_jaw_chuan")
);

-- dari 2026-08-12_create_fbd_jaw_chuan.sql
CREATE TABLE IF NOT EXISTS "kendala_fbd_jaw_chuan" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_fbd_glatt.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_fbd_glatt" (
  "id_fbd_glatt" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "panel_fbd" varchar(255) DEFAULT 'OK',
  "hmi_panel_fbd" varchar(255) DEFAULT 'OK',
  "seal_bagtight" varchar(255) DEFAULT 'OK',
  "container_up_down" varchar(255) DEFAULT 'OK',
  "shaking" varchar(255) DEFAULT 'OK',
  "pressure_gauge_damper" varchar(255) DEFAULT 'OK',
  "seal_container" varchar(255) DEFAULT 'OK',
  "guarding_pengunci_kontainer" varchar(255) DEFAULT 'OK',
  "container_mesh_dan_roda" varchar(255) DEFAULT 'OK',
  "filter_dan_bag_tight" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_fbd_glatt")
);

-- dari 2026-08-12_create_fbd_glatt.sql
CREATE TABLE IF NOT EXISTS "kendala_fbd_glatt" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_supermixer.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_supermixer" (
  "id_supermixer" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "pressure_gauge" varchar(255) DEFAULT 'OK',
  "timer" varchar(255) DEFAULT 'OK',
  "chopper" varchar(255) DEFAULT 'OK',
  "agitator" varchar(255) DEFAULT 'OK',
  "valve_hopper" varchar(255) DEFAULT 'OK',
  "discharge_valve" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_supermixer")
);

-- dari 2026-08-12_create_supermixer.sql
CREATE TABLE IF NOT EXISTS "kendala_supermixer" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_storage_tank.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_storage_tank" (
  "id_storage_tank" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_storage_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_storage_tank" varchar(255) DEFAULT 'OK',
  "motor_dan_gearbox" varchar(255) DEFAULT 'OK',
  "baling_baling_agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "pengunci_tutup_mainhole" varchar(255) DEFAULT 'OK',
  "clamp_ferrule" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_storage_tank")
);

-- dari 2026-08-12_create_storage_tank.sql
CREATE TABLE IF NOT EXISTS "kendala_storage_tank" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-20_add_storage_tank_tetrapak.sql -- clone storage_tank, unit fisik beda (Tetrapak vs Silverson)
CREATE TABLE IF NOT EXISTS "tb_mesin_storage_tank_tetrapak" (
  "id_storage_tank_tetrapak" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_storage_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_storage_tank" varchar(255) DEFAULT 'OK',
  "motor_dan_gearbox" varchar(255) DEFAULT 'OK',
  "baling_baling_agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "pengunci_tutup_mainhole" varchar(255) DEFAULT 'OK',
  "clamp_ferrule" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_storage_tank_tetrapak")
);

CREATE TABLE IF NOT EXISTS "kendala_storage_tank_tetrapak" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_mixing_tank.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_mixing_tank" (
  "id_mixing_tank" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mixing_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_mixing_tank" varchar(255) DEFAULT 'OK',
  "body_panel_hmi" varchar(255) DEFAULT 'OK',
  "agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_mixing_tank")
);

-- dari 2026-08-12_create_mixing_tank.sql
CREATE TABLE IF NOT EXISTS "kendala_mixing_tank" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-19_create_master_part.sql -- master data detail part mesin
-- (foto, Metode, Alat, Standard, Durasi, Pelaksanaan), CRUD-able superadmin.
-- Pilot: baru Cosmec, mesin lain masih hardcoded di view sampai dimigrasikan.
CREATE TABLE IF NOT EXISTS "master_part" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "machine_key" varchar(50) NOT NULL,
  "field_name" varchar(100) NOT NULL,
  "label" varchar(255) NOT NULL,
  "section" varchar(255) DEFAULT NULL,
  "metode" varchar(255) DEFAULT NULL,
  "alat" varchar(255) DEFAULT NULL,
  "standard" text DEFAULT NULL,
  "durasi" varchar(50) DEFAULT NULL,
  "pelaksanaan" varchar(255) DEFAULT NULL,
  "highlight" varchar(20) DEFAULT NULL,
  "image_path" varchar(500) DEFAULT NULL,
  "urutan" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_master_part_machine_field" UNIQUE ("machine_key", "field_name")
);


-- Kolom tambahan dari migration ALTER TABLE
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "bearing_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "bearing_pisau_sachet_cutting" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "final_cutting" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "per_transmisi_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "filling_pump" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "bantalan_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "tb_mesin_joeya" ADD COLUMN IF NOT EXISTS "isolasi_tahan_panas" varchar(255) DEFAULT NULL;

-- dari 2026-08-31_create_granulator.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_granulator" (
  "id_granulator" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "perforated_mesh" varchar(255) DEFAULT 'OK',
  "baling_baling_pisau" varchar(255) DEFAULT 'OK',
  "seal_corong" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_granulator")
);

CREATE TABLE IF NOT EXISTS "kendala_granulator" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-31_create_check_weigher.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_check_weigher" (
  "id_check_weigher" integer GENERATED BY DEFAULT AS IDENTITY,
  "lengan_rejector" varchar(255) DEFAULT 'OK',
  "body_mesin_check_weigher" varchar(255) DEFAULT 'OK',
  "vanbelt" varchar(255) DEFAULT 'OK',
  "belt_check_weigher" varchar(255) DEFAULT 'OK',
  "roller_dan_bearing" varchar(255) DEFAULT 'OK',
  "pelumasan_roller_dan_bearing" varchar(255) DEFAULT 'OK',
  "bearing_roller" varchar(255) DEFAULT 'OK',
  "kaki_kaki" varchar(255) DEFAULT 'OK',
  "pengecekan_belt_check_weigher" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_check_weigher")
);

CREATE TABLE IF NOT EXISTS "kendala_check_weigher" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-31_create_conveyor_sig.sql
CREATE TABLE IF NOT EXISTS "tb_mesin_conveyor_sig" (
  "id_conveyor_sig" integer GENERATED BY DEFAULT AS IDENTITY,
  "meja" varchar(255) DEFAULT 'OK',
  "konveyor_belt_flexible_konveyor" varchar(255) DEFAULT 'OK',
  "badan_konveyor" varchar(255) DEFAULT 'OK',
  "sensor_untuk_batch" varchar(255) DEFAULT 'OK',
  "roller" varchar(255) DEFAULT 'OK',
  "rantai_penggerak_utama" varchar(255) DEFAULT 'OK',
  "pengecekan_konveyor_belt_flexible_konveyor" varchar(255) DEFAULT 'OK',
  "pengecekan_roller" varchar(255) DEFAULT 'OK',
  "sensor" varchar(255) DEFAULT 'OK',
  "control_panel" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_conveyor_sig")
);

CREATE TABLE IF NOT EXISTS "kendala_conveyor_sig" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);



