-- Skema PostgreSQL Form AM
-- Digenerate dari ddl_dml.sql + database/migrations/*.sql
-- Tabel pabrik sebelah (33) dan illapak_1..12 legacy TIDAK disertakan.

CREATE TABLE IF NOT EXISTS "approval" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "area_id" (
  "id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY,
  "Timestamp" varchar(255) DEFAULT NULL,
  "id_log" varchar(255) DEFAULT NULL,
  "Action" varchar(255) DEFAULT NULL,
  "TableName" varchar(255) DEFAULT NULL,
  "UserID" varchar(255) DEFAULT NULL,
  "SQLQuery" text DEFAULT NULL,
  "ServerIP" varchar(255) DEFAULT NULL,
  "RequestURL" varchar(255) DEFAULT NULL,
  "RequestData" text DEFAULT NULL,
  "RequestCompleted" varchar(255) DEFAULT NULL,
  "RequestMsg" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("log_id")
);

CREATE TABLE IF NOT EXISTS "kategori" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "korelasi_id" integer NOT NULL,
  "kategori" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "kendala" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "kendala" varchar(255) NOT NULL,
  "mesin" varchar(255) DEFAULT NULL,
  "line" varchar(255) DEFAULT NULL,
  "user_followup" varchar(255) DEFAULT NULL,
  "action" varchar(255) DEFAULT NULL,
  "status" varchar(255) DEFAULT NULL,
  "date_update" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

CREATE TABLE IF NOT EXISTS "klasifikasi" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "korelasi" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "line" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "line_name" varchar(255) NOT NULL,
  "area_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mesin" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama_mesin" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
  "permission_id" integer GENERATED BY DEFAULT AS IDENTITY,
  "role_id" integer NOT NULL,
  "page_name" varchar(255) NOT NULL,
  "action_name" varchar(255) NOT NULL,
  PRIMARY KEY ("permission_id")
);

CREATE TABLE IF NOT EXISTS "roles" (
  "role_id" integer GENERATED BY DEFAULT AS IDENTITY,
  "role_name" varchar(255) NOT NULL,
  PRIMARY KEY ("role_id")
);

CREATE TABLE IF NOT EXISTS "rvs" (
  "id_rvs" integer GENERATED BY DEFAULT AS IDENTITY,
  "Jalur_Konveyor" varchar(255) DEFAULT NULL,
  "Harmonika_Pick_n_Place" varchar(255) DEFAULT NULL,
  "Sealing_Cross" varchar(255) DEFAULT NULL,
  "Selang_dan_Regulator_Pick_n_Place" varchar(255) DEFAULT NULL,
  "Proximity_Sensor_Pick_n_Place" varchar(255) DEFAULT NULL,
  "Sight_Glass" varchar(255) DEFAULT NULL,
  "Acrylic_Machine_Guards" varchar(255) DEFAULT NULL,
  "Nozzle" varchar(255) DEFAULT NULL,
  "Dudukan_Shaft_Chamber" varchar(255) DEFAULT NULL,
  "Nozzle_dan_Auger" varchar(255) DEFAULT NULL,
  "Shaft_dan_Linear_Bearing_Pick_n_Place" varchar(255) DEFAULT NULL,
  "Busa_Pisau_Cross" varchar(255) DEFAULT NULL,
  "Modul_Sealing_Long" varchar(255) DEFAULT NULL,
  "Modul_Sealing_Cross" varchar(255) DEFAULT NULL,
  "Modul_No_Batch" varchar(255) DEFAULT NULL,
  "Modul_Pisau" varchar(255) DEFAULT NULL,
  "Tekanan_Angin_Suplai" varchar(255) DEFAULT NULL,
  "value_tekanan_angin" varchar(255) DEFAULT NULL,
  "Vacuum_Pad" varchar(255) DEFAULT NULL,
  "Antistatic" varchar(255) DEFAULT NULL,
  "Jarak_Slider_dengan_Nozzle" varchar(255) DEFAULT NULL,
  "value_jarak" varchar(255) DEFAULT NULL,
  "Baut_Pisau" varchar(255) DEFAULT NULL,
  "Dudukan_dan_Sensor_Housing_Nomor_Batch" varchar(255) DEFAULT NULL,
  "Roll_Penarik_Foil" varchar(255) DEFAULT NULL,
  "Slider_atau_Sendok" varchar(255) DEFAULT NULL,
  "Vacum_Mesin" varchar(300) DEFAULT NULL,
  "Bantalan_Coding" varchar(255) DEFAULT NULL,
  "Line" integer DEFAULT NULL,
  "Inspection_Nozzle_dan_Auger" varchar(300) DEFAULT NULL,
  "Kendala" text DEFAULT NULL,
  "date_created" timestamp(6) DEFAULT NULL,
  "date_updated" timestamp(6) DEFAULT NULL,
  "user_create" varchar(300) DEFAULT NULL,
  "user_approve" varchar(300) DEFAULT NULL,
  "approval" varchar(300) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "Kabel_Heater_Sealing" varchar(255) DEFAULT NULL,
  "Karet_Intermediete" varchar(255) DEFAULT NULL,
  "area_id" integer DEFAULT NULL,
  "kategori_tag" integer NOT NULL DEFAULT 0,
  "korelasi_tag" integer NOT NULL DEFAULT 0,
  "kategori_ketidaksesuaian" integer NOT NULL DEFAULT 0,
  "id_tagging" integer NOT NULL DEFAULT 0,
  "bukaan_slider" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_rvs")
);

CREATE TABLE IF NOT EXISTS "sig" (
  "id_sig" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_cross_dan_vertikal" varchar(255) DEFAULT NULL,
  "guarding_akrilik" varchar(255) DEFAULT NULL,
  "jalur_conveyor" varchar(255) DEFAULT NULL,
  "antistatic" varchar(255) DEFAULT NULL,
  "vacuum_hood" varchar(255) DEFAULT NULL,
  "tekanan_angin_suplai" varchar(255) DEFAULT NULL,
  "value_tekanan_angin" integer DEFAULT NULL,
  "jarak_slider_dengan_nozzle" varchar(255) DEFAULT NULL,
  "rol_penarik_sachet_dan_foil_slitting_shim" varchar(255) DEFAULT NULL,
  "pisau_belah" varchar(255) DEFAULT NULL,
  "modul_pisau" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_sig")
);

CREATE TABLE IF NOT EXISTS "kendala_sig" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

CREATE TABLE IF NOT EXISTS "tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "kategori_tag" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "tag_am" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "laporan_masuk" timestamp DEFAULT CURRENT_TIMESTAMP,
  "mesin_id" integer DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "abnormality" varchar(255) DEFAULT NULL,
  "pic" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "tag_filling_kemas" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "laporan_masuk" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "area_id" integer DEFAULT NULL,
  "line_id" integer DEFAULT NULL,
  "mesin_id" integer DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "abnormarlity" varchar(255) NOT NULL,
  "foto_abnormality" bytea DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "pic" varchar(255) NOT NULL,
  "konfirmasi_teknik" varchar(255) DEFAULT NULL,
  "penanggulangan" varchar(255) DEFAULT NULL,
  "foto_penanggulangan" bytea DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'Open',
  "laporan_tutup" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamp DEFAULT NULL,
  "bulan_dibuat" varchar(255) NOT NULL,
  "tahun_dibuat" varchar(4) NOT NULL,
  "assigned_to" integer NOT NULL,
  "tanggal_dibuat" date NOT NULL,
  "bulan_tahun" varchar(255) NOT NULL,
  "judul_project_conim" varchar(255) DEFAULT NULL,
  "latar_belakang_masalah" varchar(255) DEFAULT NULL,
  "nama_fasilitator" varchar(255) DEFAULT NULL,
  "nama_pic_conim" varchar(255) DEFAULT NULL,
  "standarisasi" varchar(255) DEFAULT NULL,
  "evaluasi_manfaat" varchar(255) DEFAULT NULL,
  "penghematan_biaya" varchar(255) DEFAULT NULL,
  "investasi" varchar(255) DEFAULT NULL,
  "kesimpulan" varchar(255) DEFAULT NULL,
  "status_conim" varchar(255) DEFAULT NULL,
  "no_wr" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "users" (
  "id_user" integer GENERATED BY DEFAULT AS IDENTITY,
  "nama" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "username" varchar(255) NOT NULL,
  "area" varchar(255) DEFAULT NULL,
  "mesin" varchar(255) DEFAULT NULL,
  "password" varchar(255) DEFAULT NULL,
  "login_session_key" varchar(255) DEFAULT NULL,
  "email_status" varchar(255) DEFAULT NULL,
  "password_expire_date" date DEFAULT NULL,
  "password_reset_key" varchar(255) DEFAULT NULL,
  "account_status" varchar(255) DEFAULT 'Pending',
  "user_role_id" integer DEFAULT NULL,
  "pict" varchar(255) DEFAULT NULL,
  "failed_login_attempts" integer DEFAULT 0,
  PRIMARY KEY ("id_user")
);

-- dari 2026-08-07_create_joeya.sql
CREATE TABLE IF NOT EXISTS "joeya" (
  "id_joeya" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "jalur_konveyor_sachet" varchar(255) DEFAULT NULL,
  "collecting_plate_seluncuran_sachet" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_joeya")
);

-- dari 2026-08-07_create_joeya.sql
CREATE TABLE IF NOT EXISTS "kendala_joeya" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-07_create_illapak_1_2.sql
CREATE TABLE IF NOT EXISTS "illapak_1_2" (
  "id_illapak_1_2" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "position_indicator_sealing_vertical" varchar(255) DEFAULT NULL,
  "vacum_sliter" varchar(255) DEFAULT NULL,
  "piston_pengisian" varchar(255) DEFAULT NULL,
  "pneumatic_valves_pengisian" varchar(255) DEFAULT NULL,
  "baut_sealing_vertikal" varchar(255) DEFAULT NULL,
  "rubber_penarik_foil" varchar(255) DEFAULT NULL,
  "sensor_eyemark_dan_sambungan_foil" varchar(255) DEFAULT NULL,
  "guarding_mesin" varchar(255) DEFAULT NULL,
  "pressure_blow_sealing_vertical" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "pengunci_nozzle_pengisian" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_illapak_1_2")
);

-- dari 2026-08-07_create_illapak_1_2.sql
CREATE TABLE IF NOT EXISTS "kendala_illapak_1_2" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer NOT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) NOT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- dari 2026-08-07_create_illapak_3_12.sql
CREATE TABLE IF NOT EXISTS "illapak_3_12" (
  "id_illapak_3_12" integer GENERATED BY DEFAULT AS IDENTITY,
  "sealing_horizontal" varchar(255) DEFAULT NULL,
  "sealing_vertikal" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "roller_foil_film" varchar(255) DEFAULT NULL,
  "position_indicator_sealing_vertical" varchar(255) DEFAULT NULL,
  "vacum_sliter" varchar(255) DEFAULT NULL,
  "alarm_temperature" varchar(255) DEFAULT NULL,
  "piston_pengisian" varchar(255) DEFAULT NULL,
  "pneumatic_valves_pengisian" varchar(255) DEFAULT NULL,
  "baut_sealing_vertikal" varchar(255) DEFAULT NULL,
  "rubber_penarik_foil" varchar(255) DEFAULT NULL,
  "sensor_eyemark_dan_sambungan_foil" varchar(255) DEFAULT NULL,
  "guarding_mesin" varchar(255) DEFAULT NULL,
  "pressure_blow_sealing_vertical" varchar(255) DEFAULT NULL,
  "inkjet" varchar(255) DEFAULT NULL,
  "pengunci_nozzle_pengisian" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_illapak_3_12")
);

-- dari 2026-08-07_create_illapak_3_12.sql
CREATE TABLE IF NOT EXISTS "kendala_illapak_3_12" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer NOT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) NOT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- dari 2026-08-07_create_unifill_b.sql
CREATE TABLE IF NOT EXISTS "unifill_b" (
  "id_unifill_b" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor" varchar(255) DEFAULT NULL,
  "cutting_unit" varchar(255) DEFAULT NULL,
  "neck_sealing_unit" varchar(255) DEFAULT NULL,
  "nozzle" varchar(255) DEFAULT NULL,
  "tekanan_angin" varchar(255) DEFAULT NULL,
  "temperature_air_pendingin" varchar(255) DEFAULT NULL,
  "piston_valves_dan_selang_pengisian" varchar(255) DEFAULT NULL,
  "buffer_roller_dispenser" varchar(255) DEFAULT NULL,
  "sensory_eyemark_sensor_redaksi" varchar(255) DEFAULT NULL,
  "cylinder_grip" varchar(255) DEFAULT NULL,
  "timing_belt_pengisian" varchar(255) DEFAULT NULL,
  "filter_airfan" varchar(255) DEFAULT NULL,
  "guide_nozzle" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_unifill_b")
);

-- dari 2026-08-07_create_unifill_b.sql
CREATE TABLE IF NOT EXISTS "kendala_unifill_b" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_chimei.sql
CREATE TABLE IF NOT EXISTS "chimei" (
  "id_chimei" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor_produk" varchar(255) DEFAULT NULL,
  "roller_opp" varchar(255) DEFAULT NULL,
  "rantai_opp" varchar(255) DEFAULT NULL,
  "bearing_break_opp" varchar(255) DEFAULT NULL,
  "rantai_motor_utama_cam" varchar(255) DEFAULT NULL,
  "as_pendorong_pack" varchar(255) DEFAULT NULL,
  "jalur_compressed_air" varchar(255) DEFAULT NULL,
  "air_regulator" varchar(255) DEFAULT NULL,
  "sensor_produk_opp_pack" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_chimei")
);

-- dari 2026-08-11_create_chimei.sql
CREATE TABLE IF NOT EXISTS "kendala_chimei" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_temach.sql
CREATE TABLE IF NOT EXISTS "temach" (
  "id_temach" integer GENERATED BY DEFAULT AS IDENTITY,
  "conveyor_produk" varchar(255) DEFAULT NULL,
  "pusher_pendorong_pack" varchar(255) DEFAULT NULL,
  "turet" varchar(255) DEFAULT NULL,
  "cam" varchar(255) DEFAULT NULL,
  "lubrikasi_bearing_konveyor" varchar(255) DEFAULT NULL,
  "jalur_compressed_air" varchar(255) DEFAULT NULL,
  "air_regulator" varchar(255) DEFAULT NULL,
  "heater_a_f" varchar(255) DEFAULT NULL,
  "baut_turet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_temach")
);

-- dari 2026-08-11_create_temach.sql
CREATE TABLE IF NOT EXISTS "kendala_temach" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jihcheng.sql
CREATE TABLE IF NOT EXISTS "jihcheng" (
  "id_jihcheng" integer GENERATED BY DEFAULT AS IDENTITY,
  "konveyor_belt" varchar(255) DEFAULT NULL,
  "flexible_konveyor_u" varchar(255) DEFAULT NULL,
  "suction_cup" varchar(255) DEFAULT NULL,
  "pocket_pembawa_tube_dan_pack" varchar(255) DEFAULT NULL,
  "shaft_dan_bushing_pusher" varchar(255) DEFAULT NULL,
  "bearing_rantai_tube_cam_pusher" varchar(255) DEFAULT NULL,
  "rantai_penggerak_utama_pocket_tube_pack" varchar(255) DEFAULT NULL,
  "regulator_angin_utama" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_tube_pack_nozzle_lem" varchar(255) DEFAULT NULL,
  "pengecekan_tombol_emergency" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jihcheng")
);

-- dari 2026-08-11_create_jihcheng.sql
CREATE TABLE IF NOT EXISTS "kendala_jihcheng" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "jinsung_1_4" (
  "id_jinsung_1_4" integer GENERATED BY DEFAULT AS IDENTITY,
  "flexible_conveyor_infeed_belt_conveyor" varchar(255) DEFAULT NULL,
  "pocket_pembawa_sachet" varchar(255) DEFAULT NULL,
  "shaft_bushing_pusher_stacking" varchar(255) DEFAULT NULL,
  "rantai_penggerak" varchar(255) DEFAULT NULL,
  "regulator_angin_stacking_cartoning_check_weigher" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_sachet_pack_nozzle" varchar(255) DEFAULT NULL,
  "penekan_sachet" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jinsung_1_4")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "kendala_jinsung_1_4" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "jinsung_5" (
  "id_jinsung_5" integer GENERATED BY DEFAULT AS IDENTITY,
  "belt_conveyor_dan_pusher_pack" varchar(255) DEFAULT NULL,
  "pocket_pembawa_sachet" varchar(255) DEFAULT NULL,
  "shaft_bushing_pusher_piston" varchar(255) DEFAULT NULL,
  "rantai_penggerak_utama_cartoning" varchar(255) DEFAULT NULL,
  "regulator_angin_conveyor_cartoning_check_weigher" varchar(255) DEFAULT NULL,
  "regulator_angin_chamber_hot_melt" varchar(255) DEFAULT NULL,
  "sensor_sachet_pack_nozzle" varchar(255) DEFAULT NULL,
  "timing_belt_conveyor" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_jinsung_5")
);

-- dari 2026-08-11_create_jinsung.sql
CREATE TABLE IF NOT EXISTS "kendala_jinsung_5" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_best_pack.sql
CREATE TABLE IF NOT EXISTS "best_pack" (
  "id_best_pack" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_best_pack" varchar(255) DEFAULT NULL,
  "konveyor_best_pack" varchar(255) DEFAULT NULL,
  "print_head_inkjet" varchar(255) DEFAULT NULL,
  "belt_conveyor_best_pack" varchar(255) DEFAULT NULL,
  "pisau_best_pack" varchar(255) DEFAULT NULL,
  "selang_angin_best_pack" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_best_pack")
);

-- dari 2026-08-11_create_best_pack.sql
CREATE TABLE IF NOT EXISTS "kendala_best_pack" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-11_create_cosmec.sql
CREATE TABLE IF NOT EXISTS "cosmec" (
  "id_cosmec" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_panel_hmi" varchar(255) DEFAULT NULL,
  "body_mesin" varchar(255) DEFAULT NULL,
  "pengunci_bin" varchar(255) DEFAULT NULL,
  "switch_rantai" varchar(255) DEFAULT NULL,
  "as_dan_flange_tumbler" varchar(255) DEFAULT NULL,
  "baut_dan_mur_pada_flange_shaft" varchar(255) DEFAULT NULL,
  "panel_pompa_hidrolik_mesin" varchar(255) DEFAULT NULL,
  "kendala" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" varchar(255) DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" varchar(255) DEFAULT NULL,
  "kategori_tag" integer DEFAULT 0,
  "korelasi_tag" integer DEFAULT 0,
  "kategori_ketidaksesuaian" integer DEFAULT 0,
  "id_tagging" integer DEFAULT 0,
  "mesin" integer DEFAULT NULL,
  "delete_status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_cosmec")
);

-- dari 2026-08-11_create_cosmec.sql
CREATE TABLE IF NOT EXISTS "kendala_cosmec" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "klasifikasi_tag" integer DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_fbd_jaw_chuan.sql
CREATE TABLE IF NOT EXISTS "fbd_jaw_chuan" (
  "id_fbd_jaw_chuan" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "panel_fbd" varchar(255) DEFAULT 'OK',
  "tombol_tombol_pada_panel_fbd" varchar(255) DEFAULT 'OK',
  "seal_bagtight" varchar(255) DEFAULT 'OK',
  "container_up_down" varchar(255) DEFAULT 'OK',
  "shaking" varchar(255) DEFAULT 'OK',
  "pressure_gauge_damper" varchar(255) DEFAULT 'OK',
  "seal_container" varchar(255) DEFAULT 'OK',
  "guarding_pengunci_kontainer" varchar(255) DEFAULT 'OK',
  "container_mesh_dan_roda" varchar(255) DEFAULT 'OK',
  "filter_dan_bag_tight" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_fbd_jaw_chuan")
);

-- dari 2026-08-12_create_fbd_jaw_chuan.sql
CREATE TABLE IF NOT EXISTS "kendala_fbd_jaw_chuan" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_fbd_glatt.sql
CREATE TABLE IF NOT EXISTS "fbd_glatt" (
  "id_fbd_glatt" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "panel_fbd" varchar(255) DEFAULT 'OK',
  "hmi_panel_fbd" varchar(255) DEFAULT 'OK',
  "seal_bagtight" varchar(255) DEFAULT 'OK',
  "container_up_down" varchar(255) DEFAULT 'OK',
  "shaking" varchar(255) DEFAULT 'OK',
  "pressure_gauge_damper" varchar(255) DEFAULT 'OK',
  "seal_container" varchar(255) DEFAULT 'OK',
  "guarding_pengunci_kontainer" varchar(255) DEFAULT 'OK',
  "container_mesh_dan_roda" varchar(255) DEFAULT 'OK',
  "filter_dan_bag_tight" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_fbd_glatt")
);

-- dari 2026-08-12_create_fbd_glatt.sql
CREATE TABLE IF NOT EXISTS "kendala_fbd_glatt" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_supermixer.sql
CREATE TABLE IF NOT EXISTS "supermixer" (
  "id_supermixer" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "pressure_gauge" varchar(255) DEFAULT 'OK',
  "timer" varchar(255) DEFAULT 'OK',
  "chopper" varchar(255) DEFAULT 'OK',
  "agitator" varchar(255) DEFAULT 'OK',
  "valve_hopper" varchar(255) DEFAULT 'OK',
  "discharge_valve" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_supermixer")
);

-- dari 2026-08-12_create_supermixer.sql
CREATE TABLE IF NOT EXISTS "kendala_supermixer" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_storage_tank.sql
CREATE TABLE IF NOT EXISTS "storage_tank" (
  "id_storage_tank" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_storage_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_storage_tank" varchar(255) DEFAULT 'OK',
  "motor_dan_gearbox" varchar(255) DEFAULT 'OK',
  "baling_baling_agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "pengunci_tutup_mainhole" varchar(255) DEFAULT 'OK',
  "clamp_ferrule" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_storage_tank")
);

-- dari 2026-08-12_create_storage_tank.sql
CREATE TABLE IF NOT EXISTS "kendala_storage_tank" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- dari 2026-08-12_create_mixing_tank.sql
CREATE TABLE IF NOT EXISTS "mixing_tank" (
  "id_mixing_tank" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mixing_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_mixing_tank" varchar(255) DEFAULT 'OK',
  "body_panel_hmi" varchar(255) DEFAULT 'OK',
  "agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_mixing_tank")
);

-- dari 2026-08-12_create_mixing_tank.sql
CREATE TABLE IF NOT EXISTS "kendala_mixing_tank" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);


-- Kolom tambahan dari migration ALTER TABLE
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "bearing_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "bearing_pisau_sachet_cutting" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "final_cutting" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "per_transmisi_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "filling_pump" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "bantalan_sealing" varchar(255) DEFAULT NULL;
ALTER TABLE "joeya" ADD COLUMN IF NOT EXISTS "isolasi_tahan_panas" varchar(255) DEFAULT NULL;

