-- =============================================================================
-- DEPLOY KUMULATIF MIGRATION DATABASE FORM AM (SEPTEMBER 2026)
-- Target Rilis: Periode 09 - 11 September 2026 (Setelah 2026-09-08_password_reset_attempts.sql)
-- Sifat: 100% IDEMPOTENT (Aman dijalankan berulang kali tanpa error / duplikasi data)
-- Cara Eksekusi:
--   1. Buka pgAdmin -> Pilih Database Operasional (misal: form_am_plg / form_am)
--   2. Buka Query Tool -> Paste seluruh isi file ini -> Tekan F5 (Execute)
--   Atau via psql CLI:
--   psql -h <host> -U <user> -d <dbname> -f deploy_kumulatif_september_2026.sql
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. FIX ILAPAK SHIFT SCHEDULE (2026-09-09)
-- Memastikan jadwal shift master part Ilapak 1-2 & 3-12 aktif untuk shift 1, 2, 3
-- =============================================================================
UPDATE master_part
SET shift_schedule = '1,2,3'
WHERE machine_key = 'illapak_1_2'
  AND field_name IN ('position_indicator_sealing_vertical', 'vacum_sliter');

UPDATE master_part
SET shift_schedule = '1,2,3'
WHERE machine_key = 'illapak_3_12'
  AND field_name IN ('position_indicator_sealing_vertical', 'vacum_sliter', 'alarm_temperature');


-- =============================================================================
-- 2. PENAMBAHAN UNIT FISIK BEST PACK (2026-09-10)
-- Menambahkan 11 unit fisik mesin Best Pack tanpa mengubah ID legacy 35
-- =============================================================================
INSERT INTO "mesin" ("nama_mesin")
SELECT unit.nama_mesin
FROM (VALUES
  ('Kemas Best Pack - Ilapak 1'),
  ('Kemas Best Pack - SIG 5'),
  ('Kemas Best Pack - SIG 6'),
  ('Kemas Best Pack - Joyea'),
  ('Best Pack (non Inkjet) - Jinsung 1'),
  ('Best Pack (non Inkjet) - Jinsung 2'),
  ('Best Pack (non Inkjet) - Jinsung 3'),
  ('Best Pack (non Inkjet) - Jinsung 4'),
  ('Best Pack (non Inkjet) - Jinsung 5'),
  ('Best Pack (non Inkjet) - Unifill B'),
  ('Best Pack (non Inkjet) - Ilapak 11')
) AS unit(nama_mesin)
WHERE NOT EXISTS (
  SELECT 1 FROM "mesin" m WHERE m."nama_mesin" = unit.nama_mesin
);


-- =============================================================================
-- 3. SISTEM DEAKTIVASI MESIN / AUDIT-SAFE (2026-09-10)
-- Mendukung penonaktifan sementara mesin (misal overhaul/idle) tanpa menghapus data
-- =============================================================================
ALTER TABLE "mesin" ADD COLUMN IF NOT EXISTS "status_operasional" VARCHAR(20) NOT NULL DEFAULT 'AKTIF';
ALTER TABLE "mesin" ADD COLUMN IF NOT EXISTS "current_deactivation_id" INTEGER NULL;

CREATE TABLE IF NOT EXISTS "riwayat_status_mesin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mesin_id" INTEGER NOT NULL REFERENCES "mesin"("id") ON DELETE RESTRICT,
  "status" VARCHAR(20) NOT NULL DEFAULT 'DEAKTIVASI' CHECK ("status" = 'DEAKTIVASI'),
  "started_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ended_at" TIMESTAMP NULL,
  "reason" VARCHAR(255) NOT NULL,
  "notes" TEXT NULL,
  "action_by_user_id" INTEGER NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "action_by_username" VARCHAR(100) NOT NULL,
  "reactivated_by_user_id" INTEGER NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "reactivated_by_username" VARCHAR(100) NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ("ended_at" IS NULL OR "ended_at" >= "started_at")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_active_deactivation_per_machine" 
ON "riwayat_status_mesin" ("mesin_id") WHERE "ended_at" IS NULL;

CREATE INDEX IF NOT EXISTS "idx_riwayat_mesin_period" 
ON "riwayat_status_mesin" ("mesin_id", "started_at", "ended_at");


-- =============================================================================
-- 4. SISTEM TANDA TANGAN DIGITAL & ROLE OPERATOR (2026-09-10)
-- Paraf profil user, Role Operator (ID 5), dan tabel TTD digital periode AM
-- =============================================================================
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paraf_image" TEXT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "user_initials" VARCHAR(10) NULL;

-- Role Operator (ID 5)
INSERT INTO "roles" ("role_id", "role_name") OVERRIDING SYSTEM VALUE 
VALUES (5, 'Operator')
ON CONFLICT ("role_id") DO NOTHING;

SELECT setval(pg_get_serial_sequence('"roles"', 'role_id'), GREATEST(5, COALESCE((SELECT MAX("role_id") FROM "roles"), 1)));

-- Tabel am_period_signatures
CREATE TABLE IF NOT EXISTS "am_period_signatures" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mesin_slug" VARCHAR(100) NOT NULL,
  "mesin_id" INT NOT NULL,
  "bulan" INT NOT NULL CHECK ("bulan" BETWEEN 1 AND 12),
  "tahun" INT NOT NULL CHECK ("tahun" BETWEEN 2020 AND 2100),
  "periode" INT NOT NULL CHECK ("periode" IN (1, 2)),
  "document_hash" VARCHAR(64) NOT NULL,
  "operator_id" INT NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "operator_signed_at" TIMESTAMP NULL,
  "operator_token" VARCHAR(64) UNIQUE NULL,
  "spv_id" INT NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "spv_signed_at" TIMESTAMP NULL,
  "spv_token" VARCHAR(64) UNIQUE NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'draft',
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NULL,
  UNIQUE ("mesin_slug", "mesin_id", "bulan", "tahun", "periode")
);

CREATE INDEX IF NOT EXISTS "idx_aps_operator_token" 
ON "am_period_signatures" ("operator_token") WHERE "operator_token" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_aps_spv_token" 
ON "am_period_signatures" ("spv_token") WHERE "spv_token" IS NOT NULL;


-- =============================================================================
-- 5. SECURITY HARDENING & OPTIMASI INDEX KENDALA (2026-09-11)
-- Menghapus kolom Remember Me legacy & menambahkan index Foreign Key kendala
-- =============================================================================
ALTER TABLE "users" DROP COLUMN IF EXISTS "login_session_key";

CREATE INDEX IF NOT EXISTS "idx_kendala_sig_id_am" ON "kendala_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_id_am" ON "kendala_storage_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_tetrapak_id_am" ON "kendala_storage_tank_tetrapak" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_mixing_tank_id_am" ON "kendala_mixing_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_granulator_id_am" ON "kendala_granulator" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_supermixer_id_am" ON "kendala_supermixer" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_jaw_chuan_id_am" ON "kendala_fbd_jaw_chuan" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_glatt_id_am" ON "kendala_fbd_glatt" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_unifill_b_id_am" ON "kendala_unifill_b" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_temach_id_am" ON "kendala_temach" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_1_2_id_am" ON "kendala_illapak_1_2" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_3_12_id_am" ON "kendala_illapak_3_12" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_conveyor_sig_id_am" ON "kendala_conveyor_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_check_weigher_id_am" ON "kendala_check_weigher" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_chimei_id_am" ON "kendala_chimei" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_cosmec_id_am" ON "kendala_cosmec" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jihcheng_id_am" ON "kendala_jihcheng" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_1_4_id_am" ON "kendala_jinsung_1_4" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_5_id_am" ON "kendala_jinsung_5" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_joeya_id_am" ON "kendala_joeya" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_best_pack_id_am" ON "kendala_best_pack" ("id_am");

COMMIT;
