-- Idempotent update untuk instalasi Form AM yang sudah berjalan.
-- Fixture akun pengujian sengaja tidak dibuat di sini; gunakan
-- tests/fixtures/seed_phpunit_accounts.sql hanya pada lingkungan test/lokal.

BEGIN;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paraf_image" text NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "user_initials" varchar(10) NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_username" ON "users" ("username");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email_normalized" ON "users" (lower("email"));

CREATE TABLE IF NOT EXISTS "master_part_status_history" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "master_part_id" integer NOT NULL REFERENCES "master_part"("id") ON DELETE RESTRICT,
  "status" varchar(20) NOT NULL CHECK ("status" IN ('ACTIVE', 'TO')),
  "started_at" timestamp NOT NULL,
  "ended_at" timestamp NULL,
  "reason" text NULL,
  "changed_by_user_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "changed_by_username" varchar(255) NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ck_master_part_status_history_interval" CHECK ("ended_at" IS NULL OR "ended_at" > "started_at")
);
CREATE INDEX IF NOT EXISTS "idx_master_part_status_history_lookup"
  ON "master_part_status_history" ("master_part_id", "started_at", "ended_at");

-- Backfill kondisi saat ini. Histori takeout lama yang sudah direaktivasi
-- memang tidak dapat direkonstruksi dari master_part saja.
INSERT INTO "master_part_status_history"
  ("master_part_id", "status", "started_at", "ended_at", "reason", "changed_by_username")
SELECT "id", CASE WHEN "taken_out_at" IS NULL THEN 'ACTIVE' ELSE 'TO' END,
       COALESCE("taken_out_at", "active_from"::timestamp), NULL,
       "takeout_reason", "taken_out_by"
FROM "master_part" mp
WHERE NOT EXISTS (
  SELECT 1 FROM "master_part_status_history" h WHERE h."master_part_id" = mp."id"
);

UPDATE "roles" SET "role_name" = 'Staff' WHERE "role_id" = 4;

INSERT INTO "roles" ("role_id", "role_name") OVERRIDING SYSTEM VALUE
VALUES (5, 'Operator')
ON CONFLICT ("role_id") DO UPDATE SET "role_name" = EXCLUDED."role_name";
SELECT setval(
  pg_get_serial_sequence('"roles"', 'role_id'),
  GREATEST(5, COALESCE((SELECT MAX("role_id") FROM "roles"), 1))
);

CREATE TABLE IF NOT EXISTS "am_period_signatures" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "mesin_slug" varchar(100) NOT NULL,
  "mesin_id" integer NOT NULL,
  "bulan" integer NOT NULL CHECK ("bulan" BETWEEN 1 AND 12),
  "tahun" integer NOT NULL CHECK ("tahun" BETWEEN 2020 AND 2100),
  "periode" integer NOT NULL CHECK ("periode" IN (1, 2)),
  "document_hash" varchar(64) NOT NULL,
  "document_payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "signature_version" smallint NOT NULL DEFAULT 2,
  "operator_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "operator_signed_at" timestamp NULL,
  "operator_token" varchar(64) UNIQUE NULL,
  "operator_name" varchar(255) NULL,
  "operator_username" varchar(100) NULL,
  "operator_role_id" integer NULL,
  "operator_signature_mac" varchar(64) NULL,
  "spv_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "spv_signed_at" timestamp NULL,
  "spv_token" varchar(64) UNIQUE NULL,
  "spv_name" varchar(255) NULL,
  "spv_username" varchar(100) NULL,
  "spv_role_id" integer NULL,
  "spv_signature_mac" varchar(64) NULL,
  "status" varchar(20) NOT NULL DEFAULT 'draft',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("mesin_slug", "mesin_id", "bulan", "tahun", "periode")
);
CREATE INDEX IF NOT EXISTS "idx_aps_operator_token"
  ON "am_period_signatures" ("operator_token") WHERE "operator_token" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_aps_spv_token"
  ON "am_period_signatures" ("spv_token") WHERE "spv_token" IS NOT NULL;

-- Upgrade tanda tangan v1 tidak kompatibel: hapus approval lama sekali saat
-- kolom v2 pertama kali diperkenalkan, lalu simpan snapshot identitas signer.
DO $$
DECLARE had_v2 boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'am_period_signatures'
      AND column_name = 'signature_version'
  ) INTO had_v2;

  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "document_payload" jsonb NOT NULL DEFAULT '{}'::jsonb;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "signature_version" smallint NOT NULL DEFAULT 2;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "operator_name" varchar(255) NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "operator_username" varchar(100) NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "operator_role_id" integer NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "operator_signature_mac" varchar(64) NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "spv_name" varchar(255) NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "spv_username" varchar(100) NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "spv_role_id" integer NULL;
  ALTER TABLE "am_period_signatures" ADD COLUMN IF NOT EXISTS "spv_signature_mac" varchar(64) NULL;

  IF NOT had_v2 THEN DELETE FROM "am_period_signatures"; END IF;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'sig', 'joeya', 'illapak_1_2', 'illapak_3_12', 'unifill_b',
    'chimei', 'temach', 'jihcheng', 'jinsung_1_4', 'jinsung_5',
    'best_pack', 'cosmec', 'fbd_jaw_chuan', 'fbd_glatt', 'supermixer',
    'storage_tank', 'storage_tank_tetrapak', 'mixing_tank', 'granulator',
    'check_weigher', 'conveyor_sig'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I DROP COLUMN IF EXISTS no_wr', 'kendala_' || t);
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS foto_before varchar(255)', 'kendala_' || t);
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS foto_before_sha256 char(64)', 'kendala_' || t);
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS foto_before_mime varchar(50)', 'kendala_' || t);
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS foto_before_size integer', 'kendala_' || t);
	EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS created_by_user_id integer REFERENCES users(id_user) ON DELETE SET NULL', 'tb_mesin_' || t);
	EXECUTE format('UPDATE public.%I f SET created_by_user_id = u.id_user FROM users u WHERE f.created_by_user_id IS NULL AND f.user_create = u.username', 'tb_mesin_' || t);
  END LOOP;
END $$;

ALTER TABLE "users" DROP COLUMN IF EXISTS "login_session_key";

CREATE INDEX IF NOT EXISTS "idx_kendala_sig_id_am" ON "kendala_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_id_am" ON "kendala_storage_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_tetrapak_id_am" ON "kendala_storage_tank_tetrapak" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_mixing_tank_id_am" ON "kendala_mixing_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_granulator_id_am" ON "kendala_granulator" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_supermixer_id_am" ON "kendala_supermixer" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_jaw_chuan_id_am" ON "kendala_fbd_jaw_chuan" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_glatt_id_am" ON "kendala_fbd_glatt" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_unifill_b_id_am" ON "kendala_unifill_b" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_temach_id_am" ON "kendala_temach" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_1_2_id_am" ON "kendala_illapak_1_2" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_3_12_id_am" ON "kendala_illapak_3_12" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_conveyor_sig_id_am" ON "kendala_conveyor_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_check_weigher_id_am" ON "kendala_check_weigher" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_chimei_id_am" ON "kendala_chimei" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_cosmec_id_am" ON "kendala_cosmec" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jihcheng_id_am" ON "kendala_jihcheng" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_1_4_id_am" ON "kendala_jinsung_1_4" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_5_id_am" ON "kendala_jinsung_5" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_joeya_id_am" ON "kendala_joeya" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_best_pack_id_am" ON "kendala_best_pack" ("id_am");

COMMIT;
