-- Idempotent update untuk instalasi Form AM yang sudah berjalan.
-- Fixture akun pengujian sengaja tidak dibuat di sini; gunakan
-- tests/fixtures/seed_phpunit_accounts.sql hanya pada lingkungan test/lokal.

BEGIN;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paraf_image" text NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "user_initials" varchar(10) NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_username" ON "users" ("username");

UPDATE "roles" SET "role_name" = 'Staff' WHERE "role_id" = 4;

INSERT INTO "roles" ("role_id", "role_name") OVERRIDING SYSTEM VALUE
VALUES (5, 'Operator')
ON CONFLICT ("role_id") DO UPDATE SET "role_name" = EXCLUDED."role_name";
SELECT setval(
  pg_get_serial_sequence('"roles"', 'role_id'),
  GREATEST(5, COALESCE((SELECT MAX("role_id") FROM "roles"), 1))
);

CREATE TABLE IF NOT EXISTS "am_period_signatures" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "mesin_slug" varchar(100) NOT NULL,
  "mesin_id" integer NOT NULL,
  "bulan" integer NOT NULL CHECK ("bulan" BETWEEN 1 AND 12),
  "tahun" integer NOT NULL CHECK ("tahun" BETWEEN 2020 AND 2100),
  "periode" integer NOT NULL CHECK ("periode" IN (1, 2)),
  "document_hash" varchar(64) NOT NULL,
  "operator_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "operator_signed_at" timestamp NULL,
  "operator_token" varchar(64) UNIQUE NULL,
  "spv_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "spv_signed_at" timestamp NULL,
  "spv_token" varchar(64) UNIQUE NULL,
  "status" varchar(20) NOT NULL DEFAULT 'draft',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("mesin_slug", "mesin_id", "bulan", "tahun", "periode")
);
CREATE INDEX IF NOT EXISTS "idx_aps_operator_token"
  ON "am_period_signatures" ("operator_token") WHERE "operator_token" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_aps_spv_token"
  ON "am_period_signatures" ("spv_token") WHERE "spv_token" IS NOT NULL;

ALTER TABLE "users" DROP COLUMN IF EXISTS "login_session_key";

CREATE INDEX IF NOT EXISTS "idx_kendala_sig_id_am" ON "kendala_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_id_am" ON "kendala_storage_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_storage_tank_tetrapak_id_am" ON "kendala_storage_tank_tetrapak" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_mixing_tank_id_am" ON "kendala_mixing_tank" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_granulator_id_am" ON "kendala_granulator" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_supermixer_id_am" ON "kendala_supermixer" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_jaw_chuan_id_am" ON "kendala_fbd_jaw_chuan" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_fbd_glatt_id_am" ON "kendala_fbd_glatt" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_unifill_b_id_am" ON "kendala_unifill_b" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_temach_id_am" ON "kendala_temach" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_1_2_id_am" ON "kendala_illapak_1_2" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_illapak_3_12_id_am" ON "kendala_illapak_3_12" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_conveyor_sig_id_am" ON "kendala_conveyor_sig" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_check_weigher_id_am" ON "kendala_check_weigher" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_chimei_id_am" ON "kendala_chimei" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_cosmec_id_am" ON "kendala_cosmec" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jihcheng_id_am" ON "kendala_jihcheng" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_1_4_id_am" ON "kendala_jinsung_1_4" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_jinsung_5_id_am" ON "kendala_jinsung_5" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_joeya_id_am" ON "kendala_joeya" ("id_am");
CREATE INDEX IF NOT EXISTS "idx_kendala_best_pack_id_am" ON "kendala_best_pack" ("id_am");

COMMIT;
