-- Idempotent update untuk instalasi Form AM yang sudah berjalan.
-- Fixture akun pengujian sengaja tidak dibuat di sini; gunakan
-- tests/fixtures/seed_phpunit_accounts.sql hanya pada lingkungan test/lokal.

BEGIN;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paraf_image" text NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "user_initials" varchar(10) NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_username" ON "users" ("username");

INSERT INTO "roles" ("role_id", "role_name") OVERRIDING SYSTEM VALUE
VALUES (5, 'Operator')
ON CONFLICT ("role_id") DO UPDATE SET "role_name" = EXCLUDED."role_name";
SELECT setval(
  pg_get_serial_sequence('"roles"', 'role_id'),
  GREATEST(5, COALESCE((SELECT MAX("role_id") FROM "roles"), 1))
);

CREATE TABLE IF NOT EXISTS "am_period_signatures" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "mesin_slug" varchar(100) NOT NULL,
  "mesin_id" integer NOT NULL,
  "bulan" integer NOT NULL CHECK ("bulan" BETWEEN 1 AND 12),
  "tahun" integer NOT NULL CHECK ("tahun" BETWEEN 2020 AND 2100),
  "periode" integer NOT NULL CHECK ("periode" IN (1, 2)),
  "document_hash" varchar(64) NOT NULL,
  "operator_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "operator_signed_at" timestamp NULL,
  "operator_token" varchar(64) UNIQUE NULL,
  "spv_id" integer NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "spv_signed_at" timestamp NULL,
  "spv_token" varchar(64) UNIQUE NULL,
  "status" varchar(20) NOT NULL DEFAULT 'draft',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("mesin_slug", "mesin_id", "bulan", "tahun", "periode")
);
CREATE INDEX IF NOT EXISTS "idx_aps_operator_token"
  ON "am_period_signatures" ("operator_token") WHERE "operator_token" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_aps_spv_token"
  ON "am_period_signatures" ("spv_token") WHERE "spv_token" IS NOT NULL;

COMMIT;
