-- Migration for Conveyor SIG (Wrapping dan Pack Cartoning)
CREATE TABLE IF NOT EXISTS "tb_mesin_conveyor_sig" (
  "id_conveyor_sig" integer GENERATED BY DEFAULT AS IDENTITY,
  "meja" varchar(255) DEFAULT 'OK',
  "konveyor_belt_flexible_konveyor" varchar(255) DEFAULT 'OK',
  "badan_konveyor" varchar(255) DEFAULT 'OK',
  "sensor_untuk_batch" varchar(255) DEFAULT 'OK',
  "roller" varchar(255) DEFAULT 'OK',
  "rantai_penggerak_utama" varchar(255) DEFAULT 'OK',
  "pengecekan_konveyor_belt_flexible_konveyor" varchar(255) DEFAULT 'OK',
  "pengecekan_roller" varchar(255) DEFAULT 'OK',
  "sensor" varchar(255) DEFAULT 'OK',
  "control_panel" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_conveyor_sig")
);

CREATE TABLE IF NOT EXISTS "kendala_conveyor_sig" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- Mesin Conveyor SIG dropdown units
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Conveyor SIG 5' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Conveyor SIG 5');
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Conveyor SIG 6' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Conveyor SIG 6');

-- Master parts Conveyor SIG
INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan") VALUES
  ('conveyor_sig', 'meja', 'Meja', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Lap kering', 'Bersih dari kotoran', '2''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig meja.png', 1),
  ('conveyor_sig', 'konveyor_belt_flexible_konveyor', 'Konveyor belt, Flexible Konveyor', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Lap kering', 'Bersih dari kotoran', '2''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig konveyor belt flexible konveyor.png', 2),
  ('conveyor_sig', 'badan_konveyor', 'Badan Konveyor', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Lap kering', 'Bersih dari kotoran', '2''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig badan konveyor.png', 3),
  ('conveyor_sig', 'sensor_untuk_batch', 'Sensor untuk batch', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Lap Kain dan Air', 'Bersih dari kotoran', '2''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig sensor untuk batch.png', 4),
  ('conveyor_sig', 'roller', 'Roller', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Lap Kain dan Air', 'Bersih dari kotoran', '15''', 'Mingguan', 'mingguan', 'assets/images/conveyor_sig/conveyor_sig roller.png', 5),
  ('conveyor_sig', 'rantai_penggerak_utama', 'Rantai Penggerak Utama', 'STANDAR PELUMASAN (LUBRICATING)', 'Disemprot', 'Chain Lube', 'Terlumasi merata', '5''', 'Mingguan', 'mingguan', 'assets/images/conveyor_sig/conveyor_sig rantai penggerak utama.png', 6),
  ('conveyor_sig', 'pengecekan_konveyor_belt_flexible_konveyor', 'Konveyor belt, Flexible Konveyor', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tekanan minimal 4 bar', '1''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig pengecekan konveyor belt flexible konveyor.png', 7),
  ('conveyor_sig', 'pengecekan_roller', 'Roller', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tekanan 1.5 - 3 bar', '1''', 'Harian', NULL, 'assets/images/conveyor_sig/conveyor_sig pengecekan roller.png', 8),
  ('conveyor_sig', 'sensor', 'Sensor', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Tes Fungsi', 'Visual Control', 'Sensor berfungsi', '5''', 'Mingguan', 'mingguan', 'assets/images/conveyor_sig/conveyor_sig sensor.png', 9),
  ('conveyor_sig', 'control_panel', 'Control Panel', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Tes Fungsi', 'Visual Control', 'Panel berfungsi', '5''', 'Mingguan', 'mingguan', 'assets/images/conveyor_sig/conveyor_sig control panel.png', 10)
ON CONFLICT ("machine_key", "field_name") DO NOTHING;
