-- =============================================================================
-- Migrasi: Sistem Tanda Tangan Digital & Paraf Form AM
-- Tanggal: 2026-09-10
-- Deskripsi:
--   1. Kolom paraf & inisial di tabel users
--   2. Role Operator baru (role_id=5)
--   3. Tabel am_period_signatures untuk TTD digital
-- =============================================================================

-- 1. Tambahan kolom pada tabel users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paraf_image" TEXT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "user_initials" VARCHAR(10) NULL;

-- 2. Role Operator (hak Staff + bisa TTD form periode)
INSERT INTO "roles" ("role_id", "role_name") OVERRIDING SYSTEM VALUE VALUES (5, 'Operator')
ON CONFLICT ("role_id") DO NOTHING;
SELECT setval(pg_get_serial_sequence('"roles"', 'role_id'), GREATEST(5, COALESCE((SELECT MAX("role_id") FROM "roles"), 1)));

-- 3. Tabel pencatatan tanda tangan digital per periode
CREATE TABLE IF NOT EXISTS "am_period_signatures" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "mesin_slug" VARCHAR(100) NOT NULL,
  "mesin_id" INT NOT NULL,
  "bulan" INT NOT NULL CHECK ("bulan" BETWEEN 1 AND 12),
  "tahun" INT NOT NULL CHECK ("tahun" BETWEEN 2020 AND 2100),
  "periode" INT NOT NULL CHECK ("periode" IN (1, 2)),
  "document_hash" VARCHAR(64) NOT NULL,
  "operator_id" INT NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "operator_signed_at" TIMESTAMP NULL,
  "operator_token" VARCHAR(64) UNIQUE NULL,
  "spv_id" INT NULL REFERENCES "users"("id_user") ON DELETE SET NULL,
  "spv_signed_at" TIMESTAMP NULL,
  "spv_token" VARCHAR(64) UNIQUE NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'draft',
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("mesin_slug", "mesin_id", "bulan", "tahun", "periode")
);

-- Index untuk pencarian cepat berdasarkan token (scan QR Code)
CREATE INDEX IF NOT EXISTS "idx_aps_operator_token" ON "am_period_signatures" ("operator_token") WHERE "operator_token" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_aps_spv_token" ON "am_period_signatures" ("spv_token") WHERE "spv_token" IS NOT NULL;
