-- Immutable metadata snapshot per submitted AM form.
CREATE TABLE IF NOT EXISTS "form_part_snapshot" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_key" varchar(100) NOT NULL,
  "form_id" integer NOT NULL,
  "field_name" varchar(255) NOT NULL,
  "label" varchar(255) NOT NULL,
  "section" text NULL,
  "metode" text NULL,
  "alat" text NULL,
  "standard" text NULL,
  "durasi" text NULL,
  "pelaksanaan" text NULL,
  "highlight" varchar(100) NULL,
  "image_path" text NULL,
  "urutan" integer NULL,
  "snapshot_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_form_part_snapshot" UNIQUE ("machine_key", "form_id", "field_name")
);

CREATE INDEX IF NOT EXISTS "idx_form_part_snapshot_record"
  ON "form_part_snapshot" ("machine_key", "form_id", "urutan");

-- Best-effort backfill for records that already existed before snapshots.
-- Future records are snapshotted by BaseMachineController at submit time.
DO $$
DECLARE
  form_table text;
  machine_key_value text;
  id_column text;
BEGIN
  FOR form_table IN SELECT table_name FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name LIKE 'tb_mesin_%'
  LOOP
    machine_key_value := substr(form_table, 11);
    id_column := 'id_' || machine_key_value;
    EXECUTE format($fmt$
      INSERT INTO "form_part_snapshot"
        ("machine_key", "form_id", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
      SELECT %L, r.%I, m."field_name", m."label", m."section", m."metode", m."alat", m."standard", m."durasi", m."pelaksanaan", m."highlight", m."image_path", m."urutan"
      FROM %I r
      JOIN "master_part" m ON m."machine_key" = %L
        AND m."active_from" <= COALESCE(r."operational_date", r."created_at"::date)
        AND (m."created_at" IS NULL OR m."created_at" <= r."created_at")
        AND (m."taken_out_at" IS NULL OR m."taken_out_at" > r."created_at")
      ON CONFLICT ("machine_key", "form_id", "field_name") DO NOTHING
    $fmt$, machine_key_value, id_column, form_table, machine_key_value);
  END LOOP;
END $$;