-- Migration for Check Weigher (Wrapping dan Pack Cartoning)
CREATE TABLE IF NOT EXISTS "tb_mesin_check_weigher" (
  "id_check_weigher" integer GENERATED BY DEFAULT AS IDENTITY,
  "lengan_rejector" varchar(255) DEFAULT 'OK',
  "body_mesin_check_weigher" varchar(255) DEFAULT 'OK',
  "vanbelt" varchar(255) DEFAULT 'OK',
  "belt_check_weigher" varchar(255) DEFAULT 'OK',
  "roller_dan_bearing" varchar(255) DEFAULT 'OK',
  "pelumasan_roller_dan_bearing" varchar(255) DEFAULT 'OK',
  "bearing_roller" varchar(255) DEFAULT 'OK',
  "kaki_kaki" varchar(255) DEFAULT 'OK',
  "pengecekan_belt_check_weigher" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_check_weigher")
);

CREATE TABLE IF NOT EXISTS "kendala_check_weigher" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- Mesin Check Weigher dropdown units
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Check Weigher Jinsung 1' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Check Weigher Jinsung 1');
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Check Weigher Jinsung 2' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Check Weigher Jinsung 2');
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Check Weigher Jinsung 3' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Check Weigher Jinsung 3');
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Check Weigher Jinsung 4' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Check Weigher Jinsung 4');
INSERT INTO "mesin" ("nama_mesin")
SELECT 'Check Weigher Jinsung 5' WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Check Weigher Jinsung 5');

-- Master parts
INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan") VALUES
  ('check_weigher', 'lengan_rejector', 'Lengan Rejector', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Qulitec dan Air', 'Bersih dari kotoran', '2''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher lengan rejector.png', 1),
  ('check_weigher', 'body_mesin_check_weigher', 'Body Mesin Check Weigher', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Qulitec dan Air', 'Bersih dari kotoran', '5''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher body mesin check weigher.png', 2),
  ('check_weigher', 'vanbelt', 'Vanbelt', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Qulitec dan Air', 'Bersih dan Tidak Lengket', '30''', 'Mingguan/Saat CM Ilapak', 'mingguan', 'assets/images/check_weigher/check_weigher vanbelt.png', 3),
  ('check_weigher', 'belt_check_weigher', 'Belt Check Weigher', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Quilltec', 'Bersih dan Tidak Lengket', '2''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher belt check weigher.png', 4),
  ('check_weigher', 'roller_dan_bearing', 'Roller dan bearing', 'STANDAR PEMBERSIHAN (CLEANING)', 'Disemprot', 'Air Gun', 'Bersih dari kotoran', '30''', 'Mingguan/Saat CM Ilapak', 'mingguan', 'assets/images/check_weigher/check_weigher roller dan bearing.png', 5),
  ('check_weigher', 'pelumasan_roller_dan_bearing', 'Roller dan bearing', 'STANDAR PELUMASAN (LUBRICATING)', 'Dilumasi', 'Grease', 'Terlumasi merata', '30''', 'Mingguan/Saat CM ilapak', 'mingguan', 'assets/images/check_weigher/check_weigher pelumasan roller dan bearing.png', 6),
  ('check_weigher', 'bearing_roller', 'Bearing Roller', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek, kencangkan bila perlu', 'Visual Control', 'Tidak rusak, tidak kendur', '2''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher bearing roller.png', 7),
  ('check_weigher', 'kaki_kaki', 'Kaki-Kaki', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek, kencangkan bila perlu', 'Visual Control', 'Tidak rusak, tidak kendur', '2''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher kaki kaki.png', 8),
  ('check_weigher', 'pengecekan_belt_check_weigher', 'Belt Check Weigher', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek, kencangkan bila perlu', 'Visual Control', 'Tidak sobek', '5''', 'Harian', NULL, 'assets/images/check_weigher/check_weigher pengecekan belt check weigher.png', 9)
ON CONFLICT ("machine_key", "field_name") DO NOTHING;
