-- Rate limit reset password internal without retaining NIK/email in plaintext.
CREATE TABLE IF NOT EXISTS "password_reset_attempts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ip_address" varchar(45) NOT NULL,
  "identifier_hash" varchar(64) NOT NULL,
  "attempt_time" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "idx_reset_ip_time" ON "password_reset_attempts" ("ip_address", "attempt_time");
CREATE INDEX IF NOT EXISTS "idx_reset_ident_time" ON "password_reset_attempts" ("identifier_hash", "attempt_time");
