-- Master data detail part mesin (foto, Metode, Alat, Standard, Durasi,
-- Pelaksanaan) -- sebelumnya hardcoded di tiap view app/views/partials/{mesin}/add.php
-- ($part_details, $image_names, $sections). Pilot dulu buat Cosmec, mesin
-- lain masih pakai array hardcoded sampai dimigrasikan menyusul.
--
-- "highlight" gantiin logic string-matching lama yang nebak warna baris dari
-- teks "pelaksanaan" (strpos 'mingguan'/'bulanan') -- sekarang eksplisit kolom,
-- superadmin pilih langsung dari 3 opsi, gak perlu nebak dari teks bebas lagi.
CREATE TABLE IF NOT EXISTS "master_part" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "machine_key" varchar(50) NOT NULL,
  "field_name" varchar(100) NOT NULL,
  "label" varchar(255) NOT NULL,
  "section" varchar(255) DEFAULT NULL,
  "metode" varchar(255) DEFAULT NULL,
  "alat" varchar(255) DEFAULT NULL,
  "standard" text DEFAULT NULL,
  "durasi" varchar(50) DEFAULT NULL,
  "pelaksanaan" varchar(255) DEFAULT NULL,
  "highlight" varchar(20) DEFAULT NULL,
  "image_path" varchar(500) DEFAULT NULL,
  "urutan" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_master_part_machine_field" UNIQUE ("machine_key", "field_name")
);

-- Seed data Cosmec (7 part), dipindah dari app/views/partials/cosmec/add.php.
INSERT INTO "master_part"
  ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
VALUES
  ('cosmec', 'body_panel_hmi', 'Body Panel HMI', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Wypall lembab dengan Alkohol 70%', 'Bagian luar bersih dari kotoran', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec body panel hmi.png', 1),
  ('cosmec', 'body_mesin', 'Body Mesin', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Wypall lembab dengan Alkohol 70%', 'Bersih dari kotoran', '10''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec body mesin.png', 2),
  ('cosmec', 'pengunci_bin', 'Pengunci Bin', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Kencang dan tidak oblak', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec pengunci bin.png', 3),
  ('cosmec', 'switch_rantai', 'Switch Rantai', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Tes Fungsi', 'Visual Control', 'Tombol start tidak aktif jika rantai tidak terpasang', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec switch rantai.png', 4),
  ('cosmec', 'as_dan_flange_tumbler', 'As Dan Flange Tumbler', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tidak ada Retakan', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec as dan flange tumbler.png', 5),
  ('cosmec', 'baut_dan_mur_pada_flange_shaft', 'Baut Dan Mur Pada Flange Shaft', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Lengkap dan tidak ada yang retak/patah', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec baut dan mur pada flange shaft.png', 6),
  ('cosmec', 'panel_pompa_hidrolik_mesin', 'Panel Pompa Hidrolik Mesin', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tidak ada tetesan Oli', '2''', 'Harian (Setiap Awal Shift 1)', NULL, 'assets/images/cosmec/cosmec panel pompa hidrolik mesin.png', 7)
ON CONFLICT ("machine_key", "field_name") DO NOTHING;
