-- Migration for Granulator (Compounding)
CREATE TABLE IF NOT EXISTS "tb_mesin_granulator" (
  "id_granulator" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_mesin" varchar(255) DEFAULT 'OK',
  "perforated_mesh" varchar(255) DEFAULT 'OK',
  "baling_baling_pisau" varchar(255) DEFAULT 'OK',
  "seal_corong" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_granulator")
);

CREATE TABLE IF NOT EXISTS "kendala_granulator" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

INSERT INTO "mesin" ("nama_mesin")
SELECT 'Granulator'
WHERE NOT EXISTS (SELECT 1 FROM "mesin" WHERE "nama_mesin" = 'Granulator');

INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
SELECT 'granulator', 'body_mesin', 'Body Mesin', 'STANDAR PEMBERSIHAN (CLEANING)', 'Dilap', 'Wypall dan air', 'Bagian luar bersih dari kotoran', '10''', 'Harian', NULL, 'assets/images/granulator/granulator body mesin.png', 1
WHERE NOT EXISTS (SELECT 1 FROM "master_part" WHERE "machine_key" = 'granulator' AND "field_name" = 'body_mesin');

INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
SELECT 'granulator', 'perforated_mesh', 'Perforated Mesh', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tidak sobek, terpasang rapat', '1''', 'Harian', NULL, 'assets/images/granulator/granulator perforated mesh.png', 2
WHERE NOT EXISTS (SELECT 1 FROM "master_part" WHERE "machine_key" = 'granulator' AND "field_name" = 'perforated_mesh');

INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
SELECT 'granulator', 'baling_baling_pisau', 'Baling-baling Pisau', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Test Fungsi', 'Visual Control', 'Berfungsi normal, tidak bergesekan dengan mesh', '1''', 'Harian', NULL, 'assets/images/granulator/granulator baling baling pisau.png', 3
WHERE NOT EXISTS (SELECT 1 FROM "master_part" WHERE "machine_key" = 'granulator' AND "field_name" = 'baling_baling_pisau');

INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
SELECT 'granulator', 'seal_corong', 'Seal Corong', 'STANDAR PENGECEKAN & PENGENCANGAN (INSPECTION & TIGHTENING)', 'Dicek', 'Visual Control', 'Tidak sobek', '1''', 'Mingguan', 'mingguan', 'assets/images/granulator/granulator seal corong.png', 4
WHERE NOT EXISTS (SELECT 1 FROM "master_part" WHERE "machine_key" = 'granulator' AND "field_name" = 'seal_corong');
