-- Migrasi Sistem Deaktivasi Mesin (Audit-Safe & CPOB Compliant)
-- Tabel riwayat status mesin untuk mencatat kapan mesin fisik dinonaktifkan sementara dan diaktifkan kembali.
ALTER TABLE mesin ADD COLUMN IF NOT EXISTS status_operasional varchar(20) NOT NULL DEFAULT 'AKTIF';
ALTER TABLE mesin ADD COLUMN IF NOT EXISTS current_deactivation_id integer NULL;
CREATE TABLE IF NOT EXISTS riwayat_status_mesin (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesin_id integer NOT NULL REFERENCES mesin(id) ON DELETE RESTRICT,
  status varchar(20) NOT NULL DEFAULT 'DEAKTIVASI' CHECK (status = 'DEAKTIVASI'),
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at timestamp NULL,
  reason varchar(255) NOT NULL,
  notes text NULL,
  action_by_user_id integer NULL REFERENCES users(id_user) ON DELETE SET NULL,
  action_by_username varchar(100) NOT NULL,
  reactivated_by_user_id integer NULL REFERENCES users(id_user) ON DELETE SET NULL,
  reactivated_by_username varchar(100) NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_deactivation_per_machine ON riwayat_status_mesin (mesin_id) WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_riwayat_mesin_period ON riwayat_status_mesin (mesin_id, started_at, ended_at);
