CREATE TABLE IF NOT EXISTS `illapak_1_2` (
  `id_illapak_1_2` int(11) NOT NULL AUTO_INCREMENT,
  `sealing_horizontal` varchar(255) DEFAULT NULL,
  `sealing_vertikal` varchar(255) DEFAULT NULL,
  `body_mesin` varchar(255) DEFAULT NULL,
  `roller_foil_film` varchar(255) DEFAULT NULL,
  `position_indicator_sealing_vertical` varchar(255) DEFAULT NULL,
  `vacum_sliter` varchar(255) DEFAULT NULL,
  `piston_pengisian` varchar(255) DEFAULT NULL,
  `pneumatic_valves_pengisian` varchar(255) DEFAULT NULL,
  `baut_sealing_vertikal` varchar(255) DEFAULT NULL,
  `rubber_penarik_foil` varchar(255) DEFAULT NULL,
  `sensor_eyemark_dan_sambungan_foil` varchar(255) DEFAULT NULL,
  `guarding_mesin` varchar(255) DEFAULT NULL,
  `pressure_blow_sealing_vertical` varchar(255) DEFAULT NULL,
  `inkjet` varchar(255) DEFAULT NULL,
  `pengunci_nozzle_pengisian` varchar(255) DEFAULT NULL,
  `kendala` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_create` varchar(255) DEFAULT NULL,
  `user_approve` varchar(255) DEFAULT NULL,
  `approval` varchar(255) DEFAULT NULL,
  `perubahan` varchar(255) DEFAULT NULL,
  `user_perubah` varchar(255) DEFAULT NULL,
  `tanggal_perubahan` varchar(255) DEFAULT NULL,
  `kategori_tag` int(11) DEFAULT 0,
  `korelasi_tag` int(11) DEFAULT 0,
  `kategori_ketidaksesuaian` int(11) DEFAULT 0,
  `id_tagging` int(11) DEFAULT 0,
  `mesin` int(11) DEFAULT NULL,
  `delete_status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_illapak_1_2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kendala_illapak_1_2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_am` int(11) NOT NULL,
  `mesin` int(11) DEFAULT NULL,
  `nama_bagian` varchar(255) NOT NULL,
  `kendala` text DEFAULT NULL,
  `kategori_tag` int(11) DEFAULT NULL,
  `korelasi_tag` int(11) DEFAULT NULL,
  `klasifikasi_tag` int(11) DEFAULT NULL,
  `kategori_ketidaksesuaian` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `id_am` (`id_am`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
