-- Ternyata "Storage Tank" itu ada 2 unit fisik yang berbeda: Silverson (sudah
-- ada di tb_mesin_storage_tank/modul storage_tank) dan Tetrapak (baru). Modul
-- ini di-clone dari storage_tank -- isi part/SOP-nya sama persis, cuma nomor
-- seri unitnya beda (ST Liq 2 No 3..17).

CREATE TABLE IF NOT EXISTS "tb_mesin_storage_tank_tetrapak" (
  "id_storage_tank_tetrapak" integer GENERATED BY DEFAULT AS IDENTITY,
  "body_storage_tank" varchar(255) DEFAULT 'OK',
  "jalur_pipa_storage_tank" varchar(255) DEFAULT 'OK',
  "motor_dan_gearbox" varchar(255) DEFAULT 'OK',
  "baling_baling_agitator" varchar(255) DEFAULT 'OK',
  "seal_mainhole" varchar(255) DEFAULT 'OK',
  "pengunci_tutup_mainhole" varchar(255) DEFAULT 'OK',
  "clamp_ferrule" varchar(255) DEFAULT 'OK',
  "kendala" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_create" varchar(255) DEFAULT NULL,
  "user_approve" varchar(255) DEFAULT NULL,
  "approval" varchar(255) DEFAULT NULL,
  "perubahan" text DEFAULT NULL,
  "user_perubah" varchar(255) DEFAULT NULL,
  "tanggal_perubahan" timestamp DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "id_tagging" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "delete_status" integer DEFAULT 0,
  PRIMARY KEY ("id_storage_tank_tetrapak")
);

CREATE TABLE IF NOT EXISTS "kendala_storage_tank_tetrapak" (
  "id_kendala" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_am" integer DEFAULT NULL,
  "mesin" integer DEFAULT NULL,
  "nama_bagian" varchar(255) DEFAULT NULL,
  "kendala" text DEFAULT NULL,
  "kategori_tag" integer DEFAULT NULL,
  "korelasi_tag" integer DEFAULT NULL,
  "kategori_ketidaksesuaian" integer DEFAULT NULL,
  "klasifikasi_tag" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id_kendala")
);

-- 15 unit fisik Storage Tank Tetrapak (ST Liq 2 No 3..17). Nomor seri 029
-- muncul dobel buat No 11 & No 12 -- sesuai sumber data asli (dikonfirmasi user).
INSERT INTO "mesin" ("nama_mesin", "nomor_seri") VALUES
('ST Liq 2 No 3', '2BTNK02021'),
('ST Liq 2 No 4', '2BTNK02022'),
('ST Liq 2 No 5', '2BTNK02023'),
('ST Liq 2 No 6', '2BTNK02024'),
('ST Liq 2 No 7', '2BTNK02025'),
('ST Liq 2 No 8', '2BTNK02026'),
('ST Liq 2 No 9', '2BTNK02027'),
('ST Liq 2 No 10', '2BTNK02028'),
('ST Liq 2 No 11', '2BTNK02029'),
('ST Liq 2 No 12', '2BTNK02029'),
('ST Liq 2 No 13', '2BTNK02030'),
('ST Liq 2 No 14', '2BTNK02031'),
('ST Liq 2 No 15', '2BTNK02032'),
('ST Liq 2 No 16', '2BTNK02033'),
('ST Liq 2 No 17', '2BTNK02034');

-- Clone master_part rows dari storage_tank (Silverson) ke storage_tank_tetrapak --
-- isi Metode/Alat/Standard/Durasi/Pelaksanaan/foto/section/urutan/highlight sama persis.
INSERT INTO "master_part" ("machine_key", "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan")
SELECT 'storage_tank_tetrapak', "field_name", "label", "section", "metode", "alat", "standard", "durasi", "pelaksanaan", "highlight", "image_path", "urutan"
FROM "master_part" WHERE "machine_key" = 'storage_tank'
ON CONFLICT DO NOTHING;
